databases:
  - name: kredpartner-db
    plan: free

services:
  - type: web
    name: kredpartner_demo
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build && blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kredpartner-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
