import { User, UsersOnEnquires } from "@prisma/client"

interface EnquireUserInterface {
  value: number
  label: string
}

interface EnquiryUser {
  id: number
  partner: (UsersOnEnquires & {
    user: User
  })[]
  customer: UsersOnEnquires & {
    user: User
  }
  staff: (UsersOnEnquires & {
    user: User
  })[]
  users: (UsersOnEnquires & {
    user: User
  })[]
}

interface getUsersType {
  users: User[]
  nextPage: {
    take: number
    skip: number
  }
  hasMore: boolean
  count: number
}

// Generated by https://quicktype.io

export interface MSMETeaserType {
  city: string
  name: string
  state: string
  street: string
  capital: { [key: string]: string }
  pincode: string
  house_no: string
  turnover: { [key: string]: string }
  guarantee: Guarantee
  net_profit: { [key: string]: string }
  Introduction: string
  constitution: string
  other_income: { [key: string]: string }
  Incorporation: string
  Proprietorship: string
  house_property: { [key: string]: string }
  unsecured_loan: { [key: string]: string }
  business_income: { [key: string]: string }
  security_offered: SecurityOffered
  financial_charges: { [key: string]: string }
  financial_summary: string
  financial_summary1: string
  gross_total_income: { [key: string]: string }
  nature_of_business: string
  existing_facilities: { [key: string]: string }
  proposed_facilities: ProposedFacilities
  about_the_key_persons: string
}

export interface Guarantee {
  guarantee1: string
  guarantee2: string
}

export interface ProposedFacilities {
  total: string
  enhancement: string
  take_over_of_existing_facilities: string
}

export interface SecurityOffered {
  area: string
  address: string
  primary: string
  collateral: string
  market_value: string
  property_type: string
  property_owner: string
}
